### ISSUE TITLE
[Q] What is the reason to use list here [USER_REQUEST]

### ISSUE THREAD

**Issue by kiddick** [sqreen/vue-authentication-example#5]
https://github.com/sqreen/vue-authentication-example/blob/e2839d81d0cb2290a023f1a6e6d7c331bbe5e888/src/store/modules/user.js#L14

Seems str is enough:
```js
USER_REQUEST: ({commit, dispatch}) => {
```

**Comment by vouill** [comment]
Hey!

The exact value of `USER_REQUEST` can be used anywhere in your app though a $store.dispatch in this case.

This means that you want to have a single source of truth of this string.


In practice you want to do this:

import {USER_REQUEST} from 'foo/actions'

```
$store.dispatch(USER_REQUEST)
```

instead of 
```
$store.dispatch('USER_REQUEST')
```

Hope it helped!
